services:
  db:
    image: postgres:15.8-alpine3.19
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '8001:5432'
    volumes:
      - db:/var/lib/postgresql/data
volumes:
  db:
    driver: local