// import './globals.scss'
import { Noto_Sans, Nunito, Quicksand } from 'next/font/google';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const noto = Noto_Sans({
    weight: ['200', '300', '400', '500', '600', '700', '800', '900'],
    subsets: ["latin", "cyrillic"],
    style: ['normal', 'italic'],
    variable: '--font-noto'
});

const nunito = Nunito({
    subsets: ['latin', 'cyrillic'],
    style: ['normal', 'italic'],
    variable: '--font-nunito'
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className={nunito.variable}>
      <body>{children}</body>
    </html>
  )
}
