// import './globals.scss'
import { Noto_Sans, Nunito, Quicksand } from 'next/font/google';
import styles from './page.module.scss'
import { Theme, useGlobalState } from './GlobalState'
import { useUser } from '@/lib/user'
import { prisma } from '@/lib/db'

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

const noto = Noto_Sans({
    weight: ['200', '300', '400', '500', '600', '700', '800', '900'],
    subsets: ["latin", "cyrillic"],
    style: ['normal', 'italic'],
    variable: '--font-noto'
});

const nunito = Nunito({
    subsets: ['latin', 'cyrillic'],
    style: ['normal', 'italic'],
    variable: '--font-nunito'
});

export default async function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {

    const user = await useUser()
    let userData
    if (user) {
        userData = await prisma.user.findFirst({
            where: {
                id: user.id
            },
            select: {
                theme: true
            }
        })
    }

    return (
        <html lang="en" className={nunito.variable}>
            <body className={userData && userData.theme === 'dark' ? 'dark' : ''}>{children}</body>
        </html>
    )
}
